name: Package Extension Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - '[0-9]+.[0-9]+*' # Or standard versioning 1.0, 1.1

jobs:
  build:
    name: Package Extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP archive
        run: |
          zip -r bischecker.zip . -x "*.git*" -x ".github/*" -x "README.md"
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: bischecker.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
