name: Package Extension Release

on:
  push:
    tags:
      - 'v*'
      - '*.*.*'

jobs:
  build:
    name: Package Extension
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP archive
        run: |
          zip -r bischecker.zip . -x "*.git*" -x ".github/*" -x "README.md"
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: bischecker.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
